# Generated by Django 4.2.3 on 2023-07-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume2portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='GitHubURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='LinkedInURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TechnicalSkills',
            fields=[
                ('SkillID', models.AutoField(primary_key=True, serialize=False)),
                ('CodingLanguages', models.TextField()),
                ('OtherTechnologies', models.TextField()),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skills', to='resume2portfolio.user')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationDetails',
            fields=[
                ('QualificationID', models.AutoField(primary_key=True, serialize=False)),
                ('DegreeName', models.CharField(max_length=100)),
                ('YearFrom', models.PositiveIntegerField()),
                ('YearTo', models.PositiveIntegerField()),
                ('CGPA', models.FloatField()),
                ('CollegeSchoolName', models.CharField(max_length=200)),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_details', to='resume2portfolio.user')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectTitle', models.CharField(max_length=200)),
                ('ProjectLink', models.URLField(blank=True, null=True)),
                ('ProjectDescription', models.TextField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resume2portfolio.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('BioID', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=100)),
                ('AboutMe', models.TextField()),
                ('UserID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bio', to='resume2portfolio.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
