# Generated by Django 4.2.3 on 2023-07-23 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume2portfolio', '0002_remove_user_bio_remove_user_name_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationdetails',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_details', to='resume2portfolio.user'),
        ),
        migrations.AlterField(
            model_name='technicalskills',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skills', to='resume2portfolio.user'),
        ),
    ]
